---
author: "Alex Abraham"
jobtitle: "Applied Statistician"
address: "alex@alextabraham.com | 412-398-0129 | Dallas, TX"
web: "www.alextabraham.com"
github: "abrahamalex13"

output: 
  pdf_document:
    template: cv-header.latex
geometry: margin=0.5in
spacing: single
pagestyle: empty #no page number

header-includes:
  \usepackage{titlesec}
---

**Objective** Improve business decision-making, with underutilized data and statistical analysis.  
**Methods** Python, SQL, R (tidyverse); Statistical Analysis, Predictive Modeling (gradient boosting machines)


\vspace{-2truemm}


## Work Experience

**The Home Depot** \hfill _May 2022 - Present_

_Data Scientist_

  - Quantify relative price elasticities for commodity products.

**Sezzle** \hfill _Feb. 2021 - May 2022_

_Data Analyst - Credit Strategy_

  - Developed, deployed unsupervised learning algorithms for anomaly/fraud detection.
  - Developed unsupervised and supervised scoring models of customers' engagement, maintenance, and risk.
  - Developed a machine learning model of credit risk, to forecast new customers' loan repayment performance. 
  Interpreted model and recommended immediate improvements to existing credit limit model. 
  Containerized the model pipeline.
  


**Bank of America** \hfill _Mar. 2020 - Feb. 2021_

_Risk Strategy Analyst_

  - Coded backtests to evaluate competing home price prediction models. 
  - Built R Markdown workflows for automated monitoring of home price prediction accuracy.


**Federal Reserve Bank of Dallas**  \hfill _Jan. 2017 - Mar. 2020_

_Economic Programmer/Analyst - Regional Economy Research_ \hfill _Mar. 2018 - Mar. 2020_  

  - Backtested predictive models of 12-month job growth for Texas metros, in R.
  Examined 200 potential economic predictors using conventional time series models and machine learning algorithms.
  Recommended a simple historical average forecast strategy, based on model errors.
  - Re-built Texas monthly employment growth 'nowcasting' forecast model in R, from existing SAS code.
  Reduced program run-time to minutes, from 4 hours originally.
  - Compiled a database of select Federal Reserve branches' manufacturing survey microdata.
  - Analyzed business establishment relocations to Texas, using the National Establishments Time Series SQL database.
  Presented co-authored article to Houston Branch's Board of Directors and San Antonio Branch's banking council.


_Research Analyst - Regional Economy Research_ \hfill _Jan. 2017 - Mar. 2018_  

  - Supported research for Bank memos to the President, FOMC briefings, 
  Regional Economy magazine, and web publications.
      

\vspace{-2truemm}


## Education

- Texas A&M Master's in Statistics (4.00/4.00) \hfill _Fall 2018 - Spring 2021_
    - Electives: Multivariate Analysis and Statistical Learning, Time Series, Bayesian Methods, Spatial Statistics 
- Purdue University Bachelor's in Economics, Minor in Math (4.00/4.00) \hfill _Fall 2013 - Dec. 2016_


\vspace{-2truemm}


## Portfolio

_Co-Authored Dallas Fed Publications_  

- Orrenius, Pia, Madeline Zavodny, and Alex Abraham. 2020. _The Effect of Immigration on Business Dynamics and Employment_. 
  Working Paper 2004, Federal Reserve Bank of Dallas. https://doi.org/10.24149/wp2004.
- At the Heart of Texas: Texas Metros Employment and Wages Report [(link)](https://www.dallasfed.org/research/~/media/Documents/research/heart/heartoftexas.pdf)
- Texas Top-Ranked State for Firm Relocations [(link)](https://www.dallasfed.org/~/media/documents/research/swe/2018/swe1804b.pdf)
- Gone to Texas: Migration Vital to Growth in the Lone Star State 
  [(link)](https://www.dallasfed.org/~/media/documents/research/swe/2018/swe1801b.pdf)